root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/spool-worker ./cmd/spool"
bin = "./tmp/spool-worker"
args_bin = ["worker"]
include_ext = ["go", "html", "css"]
exclude_dir = [".git", "tmp", "vendor"]
