root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/spool-scheduler ./cmd/spool"
bin = "./tmp/spool-scheduler"
args_bin = ["scheduler"]
include_ext = ["go", "html", "css"]
exclude_dir = [".git", "tmp", "vendor"]
